version: "3.8"

services:
  mydevapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.aspnet/https:/root/.aspnet/https:ro
    ports:
      - "8000:8000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    tty: true
